### ISSUE TITLE
Stlipse - Lombok

### ISSUE THREAD

**Issue by mileslaw** [harawata/stlipse#2]
Stlipse form tags integration doesn't work for beans with lombok annotations (http://projectlombok.org/).  Maybe it's just a configuration issue?

**Comment by harawata** [comment]
Thanks for the report!
It seems that the information about the access modifiers of generated getter/setter is lost at some point.
I will try to narrow down the problem, but it might take some time.

**Comment by harawata** [comment]
Please let me know if 1.0.11 does not solve your problem.

**Comment by mileslaw** [comment]
Everything works great. Thank you very much.
