### ISSUE TITLE
jsp completion and validation

### ISSUE THREAD

**Issue by perceptron8** [harawata/stlipse#3]
JSP completion and validation doesn't work for properties whose types are "external".

I noticed that AST and CompilationUnit are used to get info about fields in type referenced by qualifiedName... Why not just simply iterate over fields with IType#getFields() after getting IType from IJavaProject? As IType's javadoc says, IType may represent not only source type in a compilation unit but also binary type in a class file. It seems possible to build BeanPropertyInfo without source code and syntax trees. And it may be desirable.

It is a common situation to depend on third party modules, libs and data types. Think of jar with some jaxb classes as an example. It would be very useful to have some validation and completion support in such cases.

**Comment by harawata** [comment]
IIRC, the IField returned by IType#getFields() doesn't contain enough information for further validation.
Anyway, I will look into it.
Thank you for the report!

**Comment by perceptron8** [comment]
Wow! That was quick! :) If I can help somehow, let me know.
BTW I should write about iterating over IType#getMethods() instead of IType#getFields(). What else would you need in addition to method's parameters and return types?
Thank you for the response!

**Comment by harawata** [comment]
> If I can help somehow, let me know.

Great! I will probably ask you to verify the fix before release, then.

> BTW I should write about iterating over IType#getMethods() instead of IType#getFields(). What else would you need in addition to method's parameters and return types?

I don't remember why I had to use ASTParser in the first place, but will try your suggestion.
Thank you!

**Comment by perceptron8** [comment]
It works like a charm! Thank you!

**Comment by harawata** [comment]
Oh, I was writing this comment to ask you to try it :-)
Thank you very much for the feedback!

p.s.
ASTParser is needed to analyze **source type** classes (i.e. files in the workspace) because IType for **source type** does not contain necessary information unless its _binding is resolved_.
Stlipse needs the fully-qualified name of parameter, return type, etc. to support nested properties (i.e. parent.child.grandchild...), for example.

**Comment by perceptron8** [comment]
You are right: before resolving bindings, names are unqualified. Your first answer was indeed correct.
I'd like to thank you one more time! Only at the first day you saved me hours of debugging. I'll try to give it back to community :)
Greetings from Poland!

**Comment by harawata** [comment]
You are very welcome!
And it was a nice addition indeed, so I thank you, too!
