### ISSUE TITLE
Warning in JSP for bean properties starting with upper cases

### ISSUE THREAD

**Issue by nclemeur** [harawata/stlipse#5]
It seems that stlipse does not resolve properly bean properties that have a name starting with uppercases. So if you have a bean property, name MYName, and the getter/setter getMYName/setMYName, stlipse seems to think that the bean property is mYName, resulting in the following warning in the jsp:

Writable property 'bean.MYName' not found in  com.dummy.DummyActionBean

And the auto-complete offer the option bean.mYName

I think that if a bean property start with more than one upper case letters, the property name should be taken as is...

**Comment by harawata** [comment]
Hi,

Yes, it's one of the I-will-fix-when-it's-reported tasks :-)
Give me a few days as I would like to correct another issue in the next release.

Thank you for the report!
Iwao

**Comment by nclemeur** [comment]
Hello,
Thanks for the answer. One think that I forgot to mention is that this problem is also manifesting it-self  when enabling the Annotation Processing. The problem with that is that there is a compilation error and the annotation processing has to be disabled...

Anyway, thank you for your work on that plugin, it is really helpfull.

Cheers

Nicolas

**Comment by harawata** [comment]
Glad you found it useful!

The problem (including the annotation processing error) should be fixed in 1.0.14.
Thanks again for taking the time to report this.

Regards,
Iwao
